services:
  - type: web
    name: mrxbeastyt-backend
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: FFMPEG_PATH
        value: ffmpeg
